### ISSUE TITLE
notification center icons are huge

### ISSUE THREAD

**Issue by jm3** [Fogh/SABnzbd-Alfred#4]
This is a great extension. Super handy toy for my Alfred toolbelt. One question: why are the notification center icons so gigantic? 

![notification-center-icons-too-large](https://cloud.githubusercontent.com/assets/12213/8551551/2fe59996-248c-11e5-9eaa-166ee8e5bc78.png)

none of my other apps have notification icons even remotely as large. I think you're maybe using the slot that's intended for a content preview instead of the icon spot?

It would be nice if the Sab-Alfred extension could be consistent with the other notification center apps. I'm happy to submit a PR for this if you want to point me in the right direction.

**Comment by Fogh** [comment]
The big icons is just how Alfred shows workflow icons. Workflows have no way of setting the size.

**Comment by jm3** [comment]
Oh. That's super lame. So unless I decide to switch to Growl, I can't control that at all?

**Comment by Fogh** [comment]
That is correct, as far as I know.

**Comment by jm3** [comment]
OK cool. I'll close this — filed it as a bug here: http://www.alfredforum.com/topic/6006-remove-jumbo-out-of-place-icons-in-notification-center-please/
